select * from new_schema.imdb ;

/* Exploratory Data Analysis */

/* 1. Which genres has yielded the highest average gross revenue? */
SELECT Genre, round(AVG(gross),0) AS AverageGross 
FROM new_schema.imdb
GROUP BY Genre
ORDER BY AverageGross DESC;
/* This query helps identify the most financially lucrative movie genres by calculating the average gross revenue 
for each genre. By analyzing this data, we can determine which genres generate the highest revenue on average, 
providing valuable insights for decision-making in the movie industry. This information aligns with our problem statement, 
as it helps identify the genres that yield higher revenue, thus informing strategic decisions related to future movie 
production and distribution.*/

/* 2. What is the distribution of revenue among different genres?*/
       /* Using Sub queries */
/*Understanding the distribution of revenue across genres provides insights into the diversity of revenue sources in the movie industry. 
It helps identify both dominant and niche genres contributing to overall revenue. We'll use a subquery to calculate the total revenue 
for each genre and compare it to the overall revenue to determine the proportion of revenue generated by each genre.*/

SELECT 
    Genre,
    SUM(Gross) AS TotalRevenue,
    SUM(Gross) / (SELECT SUM(Gross) FROM new_schema.imdb) * 100 AS RevenuePercentage
FROM 
    new_schema.imdb
GROUP BY 
    Genre
ORDER BY 
    TotalRevenue DESC;
/* This query calculates the total revenue for each genre using a subquery to compute the overall revenue of all genres.
The percentage of revenue contributed by each genre is calculated by dividing its total revenue by the overall revenue 
and multiplying by 100. By analyzing the distribution of revenue among genres, we gain insights into the relative importance 
of different genres in contributing to the overall revenue of the movie industry.*/

/*3. How does the average revenue vary over the years for different genres? */
SELECT Genre, Released_Year, AVG(Gross) AS AverageRevenue
FROM new_schema.imdb
GROUP BY Genre, Released_Year
ORDER BY Released_Year, AverageRevenue DESC;

/*4. Which genres have got the highest and lowest ratings on IMDB? */
    /* Common Table Expressions */
WITH RatingRank AS (
    SELECT Genre, AVG(IMDB_Rating) AS AvgRating,
           ROW_NUMBER() OVER (ORDER BY AVG(IMDB_Rating) DESC) AS RatingRankHigh,
           ROW_NUMBER() OVER (ORDER BY AVG(IMDB_Rating) ASC) AS RatingRankLow
    FROM new_schema.imdb
    GROUP BY Genre
)
SELECT Genre, AvgRating, RatingRankHigh, RatingRankLow
FROM RatingRank
WHERE RatingRankHigh = 1 OR RatingRankLow = 1;

/*5. What is the average runtime for movies in each genre, and how does it vary across genres? */
WITH GenreAvgRuntime AS (
    SELECT 
        Genre,
        AVG(Runtime) AS AvgRuntime,
        MIN(Runtime) AS MinRuntime,
        MAX(Runtime) AS MaxRuntime,
        PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY Runtime) AS MedianRuntime
    FROM
        new_schema.imdb
    GROUP BY
        Genre
        )
SELECT
    Genre,
    AvgRuntime,
    MinRuntime,
    MaxRuntime,
    MedianRuntime
FROM
    GenreAvgRuntime
ORDER BY
    AvgRuntime DESC;

/* 6. What is the average runtime and gross revenue for movies in each genre? */
SELECT 
    Genre,
    ROUND(AVG(Runtime),2) AS AverageRuntime,
    AVG(Gross) AS AverageRevenue
FROM
    new_schema.imdb
GROUP BY
    Genre
ORDER BY
    AverageRevenue DESC;

/*7. What is the range of revenue (both maximum and minimum) and IMDb ratings for each genre? */
-- Query to calculate the range of revenue and IMDb ratings for each genre
SELECT
    Genre,
    MAX(Gross) AS Max_Revenue,
    MIN(Gross) AS Min_Revenue,
    MAX(IMDB_Rating) AS Max_Rating,
    MIN(IMDB_Rating) AS Min_Rating
FROM
    new_schema.imdb
GROUP BY
    Genre;
    
/*8. What is the average runtime for movies in each genre */
SELECT
    Genre,
    ROUND(AVG(Runtime),2) AS Avg_Runtime
FROM
    new_schema.imdb
GROUP BY
    Genre;







 
